name: Deploy Frontend

on:
  push:
    branches:
      - main
      - supuni-dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t frontend-app .

    - name: Copy files to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "./blissme-app"
        target: "/home/ubuntu/frontend"

    - name: Deploy on EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd frontend
          docker build -t frontend-app .
          docker stop frontend-app || true
          docker rm frontend-app || true
          docker run -d -p 80:80 --name frontend-app frontend-app
